name: chatterbot-environment
channels:
  - conda-forge
  - defaults 
dependencies:
  - python=3.6
  - spacy==2.1.3
  - PyYAML==3.13
  - pip:
      - chatterbot==1.0.8
      - chatterbot-corpus==1.2.0
