name: chatterbot-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - regex==2018.1.10
  - requests==2.23.0
  - nltk==3.4
  - scikit-learn==1.0.2
  - ChatterBot==1.0.8
  - spacy==2.1.3
  - PyYAML==3.13
  - chatterbot-corpus==1.2.0
